rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode

gemfile:
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile

matrix:
  allow_failures:
    - rvm: jruby-19mode

before_install: "gem install bundler"
script: "bundle exec rake test"
sudo: false
