rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode

gemfile:
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile

before_install: "gem install bundler"
script: "bundle exec rake test"
